
	<div class="content_wrapper clearfix">
		<div class="sections_group">
			<div class="entry-content">
				<div class="section flv_sections_8" id="orientation-test">
					<div class="section_wrapper clearfix">
						<div class="items_group clearfix">
							<!-- Page Title-->
							<!-- One full width row-->
							<div class="column one column_fancy_heading">
								<div class="fancy_heading fancy_heading_icon">
									<h2 style="color:#54b141; background: url(/frontend/immagini/linea-titolo-verde.png) no-repeat bottom center; padding-bottom: 25px;">TERMS OF SERVICE</h2>
								</div>
							</div>
							<div class="column one column_column">
								<div class="column_attr ">
                                  <p align="center"><strong><em>GENERAL CONTRACTUAL CONDITIONS AND TERMS OF USE OF SERVICES</em></strong></p>























                                  <p><br>
                                    The present site (hereafter called &ldquo;Website&rdquo;) <a href="https://www.wexplore.eu">www.wexplore.eu</a> is the property of Wexplore Srl (hereafter called &ldquo;Wexplore&rdquo;), with registered office in Milan, Italy, Via Sangallo 33 – 20133, fiscal code and registry number 2120181, VAT ID IT03560330130. <br />
Wexplore observes the normative related to remotely finalized contracts pursuant to the art. 50 and subsequent articles of the Italian Legis. Decree 206/2005. We invite you to read carefully the conditions as detailed below, and to print and/or save them on another support of your choice. </p>
                                  <p><strong>1)              Object:</strong><br />
                                    <strong>1.1.           </strong>The present General Contractual Conditions and Terms of Use of Services (hereafter called &ldquo;General Conditions&rdquo;) discipline the ways and terms under which Wexplore provides the training and consultancy services (specifically career orientation), (hereafter &ldquo;Services&rdquo; or &ldquo;Service&rdquo;). The Website is accessible also to non-registered users, with reference to the list of the offered services and related prices, company information and consultation of blog with contents (&ldquo;Services accessible to all&rdquo;). All the other Services (&ldquo;Services reserved to Users&rdquo;) are delivered only to the registered Users. The Services reserved to Users can be either freely available, or be available through payment (&ldquo;Payment Services&rdquo;). In delivering the Services, Wexplore adheres to its Company Ethical Code, available at the following link https://www.wexplore.eu/en/code-ethics. <br />
                                    <strong>1.2.           </strong>The Services are delivered by Wexplore only on remote through the internet and in the way rightly and factually described at the date of the request of activation/renewal of the Service, as published on the Website, with the technical and economic specifics detailed therein, which the Client, by accepting the present General Conditions, declares expressly to know and accept. The Services offer and contents are indicated in the dedicated area on the Website, notwithstanding the right of Wexplore to suspend or revoke them in any moment; in such an event, the contracts concluded before such suspension or revocation will be honored at the agreed conditions. Any additional performances than those explicitly provided for may be delivered by Wexplore only following a specific written request by the Client in the modalities that shall be agreed on an ad hoc basis.<br />
                                    <strong>1.3.           </strong>The present General Conditions have been drafted and predisposed pursuant to the dispositions of the Italian Legislative Decree 206/2005 (Consumer Code) and Law 40/2007 (Urgent Measures for the protection of consumers, the promotion of competition, the development of economical ventures and the rise of new enterprises); these provisions are general in nature, and may be subject to modifications following the introduction of subsequent laws and/or regulations. </p>
                                  <p><strong>2)              Registration to the Website and finalization of the Services delivery contract for Services reserved to Users and Payment Services: </strong><br />
                                    2.1            With the Registration on the Website, as detailed in art. 4 below, the User declares to accept the present General Conditions in their entirety, including the content of the documents, norms, dispositions, and procedures contained therewith, making them binding for the User even before the finalization of the single contract for delivery of the Payment Services, as detailed in art. 2.2 below.<br />
                                    2.2             The contract for the delivery of Services reserved to Users, will be finalized upon the correct and punctual receipt by Wexplore of the order module of the specific Service, as filled and submitted online by the Client in every part on the Website, according to the procedures required for the finalization of online contracts, combined with the receipt of the payment confirmation for the applicable service selected by the Client, to be received via email by the Party enabled to perform such operation. The Parties agree that for any Payment Service, Wexplore will not engage in any delivery unless the payment confirmation is received. Should the payment not be received by Wexplore within 90 (ninety) days from the date of purchase, the order shall be cancelled without any further notice. The Client acknowledges and accepts that, in such a case, the Client shall not have right to any claim against Wexplore and releases the company from any liability associated with the cancellation of the order. Any amount which Wexplore should have received as down payment for a subsequently cancelled order shall be made available to the Client as detailed below.  </p>
                                  <p><strong>3)              Definitions:</strong><br />
                                    3.1.           In these General Conditions, the following words and expressions shall unless the context otherwise requires have the following meanings:<br />
  <strong><em>Service:</em></strong> the training and consultancy service (specifically career orientation) delivered through the website, as defined herewith; <br />
  <strong><em>Website:</em></strong> Wexplore&rsquo;s website, located at the address www.wexplore.eu; <br />
  <strong><em>Services accessible to all:</em></strong> the pages of the Website accessible to anyone, even without Registration;<br />
  <strong><em>User:</em></strong> any individual who has successfully concluded the registration process described herewith, accepting the present General Conditions and accepting the rights and duties hereby described; <br />
  <strong><em>Services reserved to Users</em></strong>: training and consultancy services delivered exclusively to the registered Users, free of charge or payable, delivered through specific Packages; <br />
  <strong><em>Payment Services</em></strong>: Services reserved to Users delivered upon payment, and contained in the specific Packages purchasable on the Website; <br />
  <strong><em>Packages</em></strong>: specific &ldquo;packages&rdquo;, free of charge or payable, containing the Services and available to the Users registered on the website;<br />
  <strong><em>General Conditions</em></strong>: the Contract terms and Conditions, which the User accepts upon registration by clicking on the button &ldquo;Accept&rdquo;.<br />
  <strong><em>Contract:</em></strong> the contract for the Services Reserved to Users disciplined by the General Conditions, which is finalized between Wexplore and each User as per art. 2.2 above. The General Conditions are applicable also to services that shall be delivered in the future to each User, unless otherwise provided for upon the registration or the first delivery of the new service. Some services, while still regulated by the General Conditions, may also be subject to specific terms and conditions due to their nature and/or characteristics; these specific terms and conditions shall be communicated to the Users pursuant to the modalities specified in the General Conditions.  <a name="2" id="2"></a></p>
                                  <p><strong>4)              Registration Policy</strong>:<br />
                                    4.1.           The access to the Services is allowed only to a User registered through an identification term (e-mail address) and key word (password). Upon the registration on the Website, the User will be required to provide his/herpersonal data. The User will be required to indicate his/her preferred mode of payment only upon finalization of any Contract for the delivery of Payment Services. <br />
                                    Both natural persons (provided they are legally adult) and legal entities are allowed to Register. <br />
                                    4.2.           Each User has the right to change his/her password following the instructions provided on the Website, and agrees that the provided email address and password represent the validation system for accessing the Website as User, as well as the only means to legitimize the User to access said Website. The User will therefore be liable of any action performed through the use of his/her personal nickname and password. The User commits to treat said nickname and password as confidential, and to preserve them with the utmost care.  <br />
                                    4.3.           The User commits to send timely written communication to Wexplore by recorded delivery to the address Via Sangallo 33, 20133 Milan, Italy, or via email at the address info@wexplore.eu (provided it is followed by a recorded delivery within 48 hours) of i) any unauthorized use of his/her associated nickname and password, ii) any other violation of the Website or User profile security to his/her knowledge. Following any such notice, Wexplore commits to deactivate the password under threat of violation of secrecy.  <br />
                                    4.4.           The User is required to provide some personal information upon the filling in of the registration form, whose treatment shall be pursuant to the Italian Legis. Decree 196/2003 (Privacy Code), and pursuant to the Privacy Policy provided to the User upon his/her registration, and available for consultation at the following link: https://www.wexplore.eu/en/privacy-policy. Upon acceptance of the General Conditions, the User warrants that his/her personal data are updated, correct, and entirely true, and commits to editing them in a timely manner to ensure they are updated, correct, and entirely true. </p>
                                  <p><strong>5)              Characteristics of the Services:<a name="2.1" id="2.1"></a></strong><br />
                                    5.1.           All the Services reserved to Users are delivered exclusively to the registered Users, based on the following modalities:  <br />
                                    -                online self service: downloadable documents in .pdf format, online questionnaires to fill in, videos, etc.;<br />
                                    -                video chat with a Consultant, one-to-one or group sessions; <a name="2.2" id="2.2"></a><br />
                                    -                use of blog with contents (with possibility to interact).<br />
                                    5.2.           The Services reserved to the Users, as stated above, are contained in the specific Packages purchasable by the User through the Website. <br />
                                    5.3.           The Packages containing the various Services are ordered by the registered Users as detailed in art. 2.2 above, and may be free of charge or payable. <br />
                                    5.4.           <a name="2.3" id="2.3"></a>The Services accessible to all, even without registration, are constituted by: <br />
                                    -                informative pages on services offered and prices;<br />
                                    -                information about the company;<br />
                                    -                blog with contents (reading only). <br />
  <strong>6)              Fees and Payment of Payment Services:</strong><br />
                                    6.1.           The payment for the fees related to the selected and purchased Package, if related to Payment Services, must be performed during the online subscription for each order, and in any case prior to the activation of the Service. The Service price is determined based on the applicable fees as detailed on the Website, and may vary according to the Package ordered by the Client. <br />
                                    6.2.           All fees will be subject to VAT, if applicable, which will be at the expense of the User together with any additional fiscal duty deriving from the execution of the Contract. In any event, the User expressly relieves now for then Wexplore of all responsibilities deriving from all transactions or processed payments for the Services.  <br />
                                    6.3.           Pursuant to art. 52 comma 1 lett. E) of the Italian Legis. Decree 206/2005, the Client agrees that the payment of the price for the selected Service will be processed as indicated on the Website itself.  <br />
                                    6.4.           The Client may not raise any claim or objections unless he/she has correctly paid the fees provided for in the Contract, and to provide evidence of that upon request by Wexplore. Should the payment prove invalid or be for any reason revoked or canceled by the Client, or not be processed, confirmed, or credited to Wexplore itself, the latter reserves itself the right to suspend and/or interrupt the activation and/or delivery of the Service with immediate effect, should the Service itself be already activated, leaving the person who has submitted the order all obligations related to the finalizing of the payment and to any related interests cumulated by this delay.  <br />
                                    6.5            By accepting the present General Conditions, the Client expressly agrees that the invoice will be sent and/or be made available to him/her in a digital format. <br />
                                    6.6.           Any existing credits in favor of the Client, for whichever reason due and not deriving from any Service and/or Package, for whichever reason, must be utilized by the Client for the purchase or renewal of Services provided by Wexplore within 12 (twelve) months from the date of the payment, as indicated on the Website. Shall the Client fail to exercise this right and use the cumulated credit within the said amount of time, this credit shall be definitely acquired and collected by Wexplore, and the Client may not claim to use it or to have it returned. </p>
                                  <p><strong>7)              Service activation and delivery:</strong><br />
                                    7.1.           The Client acknowledges and accepts that the procedures for the activation and, if and when applicable, the renewal of the Service, shall begin upon the finalization of the Contract related to the specific Service and/or Package purchased by the User. Wexplore shall communicate to the Client the confirmation of the activation of the Service through a dedicated email. Upon the activation of the Service, all the rights related to its usage shall be automatically transferred to the Client, who shall become the legitimate owner of the Service, as well as having the sole and exclusive accountability for its usage, and for the materials and data, including personal information, which he/she shall process through the Service itself. <br />
                                    7.2.           Wexplore reserves the right to not proceed to the activation or the renewal of the Service and/or Package, at its uncontestable discretion, in cases where:<br />
  <strong>a)</strong> the Client has been a defaulter towards Wexplore, even in past contractual relationships. In such as case, the activation of the Service may be subordinate, to Wexplore&rsquo;s discretion and following specific communication, to the compliance of the previous relationship; <br />
  <strong>b)</strong> the Client fails to provide Wexplore the documentation it requires, or provides information that are false or suspected to be such; <br />
  <strong>c)</strong> the Client has subscribed to a register of protests or is found subject to enforcement proceedings;<br />
  <strong>d)</strong> the Client is admitted or subject to an insolvency process; <br />
  <strong>e)</strong> there are technical, organizational or other motives that prove prejudicial to the activation of the Service. <br />
                                    Wexplore shall communicate to the Client the failed activation or renewal of the Package and/or Service without having to justify the motives, and will be bound to return to the Client only any amount it will have received as payment, without any additional onus or tax duty. The Parties agree that no interests of any kind shall accrue on the said amount. The Client acknowledges and agrees that he/she is entitled exclusively to the return of the amount paid to Wexplore, and is not entitled to claim any indemnity, compensation for the damage suffered, or any other claim due to the lack of activation of the Service.  <a name="3" id="3"></a><br />
                                    7.3.           After the Service ordered has been activated, the Client can access the Service through the dedicated reserved area on the Website by logging in with his/her credentials (username and password). Every page of the reserved area contains instructions on how it is best to use it. </p>
                                  <p><strong>8)              Duration, extension, termination and cancellation of the contract: </strong><br />
                                    8.1.           The Contract for the delivery of Payment Services shall have a duration equal to the time indicated for each purchased Service and/or Package, starting from the date of the activation of the Service.<br />
                                    As the date of expiry approaches Wexplore, as a courtesy and with no obligation towards the Client, may send to the email address provided by the Client, a notice indicating the expiration date and warning against the possible termination of the Service, if and when applicable. &nbsp;&nbsp; <br />
                                    8.2.           Upon the date of expiry set for the selected Package, all Services and any additional Services shall be deactivated, and the Contract shall cease to have effect, unless the Client shall choose to renew it, if and when applicable, at the fees and conditions in effect at the time of the renewal.   <br />
                                    8.3.           The User who is also a Consumer pursuant to the Italian Consumer Code may freely recede from the Contract within 14 (fourteen) working day after its finalization. The termination must be communicated to Wexplore through recorded mail delivery service. The termination may be also sent via email to the email address <a href="mailto:info@wexplore.eu">info@wexplore.eu</a>, provided it is followed by a recorded mail within the next 48 hours. In the case in which the service to be delivered by Wexplore related to the specific Package purchased by the User shall be completed, the Consumer is not entitled to recede anymore, pursuant to art. 59 of the Italian Consumer Code. Pursuant to the same art. 59, the User expressly authorizes the advance beginning of the service and expressly accepts the loss of his/her termination right following the full execution of the contract by Wexplore. <a name="4" id="4"></a></p>
                                  <p><strong>9)              Blog usage</strong>.<br />
                                    <a name="4.1" id="4.1"></a>9.1.           Upon registering to the Website pursuant to art. 4 above, each User will be allowed to comment the Blog contents on the Website as identified by his/her nickname, related to topics connected to the Service. <br />
                                    9.2.           The User is not allowed to publish on the Blog pornographic, obscene or illegal material, including but not limited to: pirate software, cracks, warez, malware, virus, phishing websites (fake login), mp3 violating the legislation on author&rsquo;s rights, material that may cause damage to others.  <a name="4.2" id="4.2"></a><br />
                                    9.2.           The registered User takes full and complete responsibility for any of his/her postings as a comment to the Blog, indemnifying and holding Wexplore harmless from any claim or controversy deriving from the use or abuse of the offered Services.  <a name="4.3" id="4.3"></a><br />
                                    9.3.           The User acknowledges that Wexplore reserves the right to access, in any moment and without notice, to its discretion, to the Blog&rsquo;s comments to ensure the compliance to the General Conditions. Wexplore reserves the right to suspend the Service whether, at its uncontestable judgement, also as signaled by third parties, it believes that the present General Conditions have been violated. The User furthermore acknowledges that Wexplore, while complying to the obligations deriving from the applicable and binding legal norms, may deliver the material posted on the Blog and/or reveal its content to the competent authorities. Wexplore is expressly authorized to insert on the Website any appropriate notice concerning the lack of any connection between Wexplore and the User, or the User&rsquo;s activity on the Blog.  <a name="4.4" id="4.4"></a><a name="4.9" id="4.9"></a><a name="5" id="5"></a><a name="5.1" id="5.1"></a><br />
                                    9.4            The User warrants that all information, programs, and data input through the Service in whichever form, area or space made available by Wexplore, is original.  <a name="5.2" id="5.2"></a><br />
                                    9.5.           Any material protected by copyright may be used only in the case the User has obtained the license and right of use of such material from the owner of the said rights, and in such a case only through written permission or license from the author and the obligation to quote the source and the existence of the license. Any photo, audio or video material from third parties or reproducing others may be used only in the case the User has obtained permission from the author and the subject portrayed. The User takes on full responsibility for the existence of such rights and licenses, completely relieving Wexplore.  <br />
  <a name="5.3" id="5.3"></a>9.6.           Furthermore, the User takes full responsibility for the exactness and truthfulness of the material inserted in the Blog, on behalf of him/herself or of others, and represents that such material is owned by right, is not contrary to imperative norms, and does not violate any distinctive sign, intellectual or industrial property right, image right, or any right of others deriving from the applicable norms or customs. In any case, the content input by the User must not be or present any pedo-pornographic, pornographic, obscene, blasphemous, or libelous trait. </p>
                                  <p><strong>10)</strong>           <strong>Minors protection</strong>:<br />
                                    10.1.        Underage individuals cannot conclude the registration process, even with the assistance of a parent or tutor.  <br />
                                    10.2.        The subjects who, through their parental responsibility over an underage person, allow him/her to use any of the Services are responsible for their behaviors online, for controlling their accesses and for any consequence deriving from an abuse of the Service from an underage individual. </p>
                                  <p><strong>11)           Functionalities of the Services:</strong><br />
                                    11.1         The Services accessible to all and the Services reserved for Users contained in the Packages ordered by the User will be normally accessible h 24 (twenty-four); however, the Client acknowledges and agrees that Wexplore may suspend and/or interrupt their provision to allow for ordinary or extraordinary maintenance interventions that may be opportune and/or necessary from time to time to the Server Farm rooms and to the servers and/or machines contained therein. <br />
                                    In such cases, Wexplore shall endeavor to complete said interventions in the shortest possible time, and to reinstate the Service as soon as it will be possible in order to minimize any damage which the Client may incur. The Client acknowledges and agrees that he/she may not put forward any claim of reimbursement, reparation, or compensation from Wexplore for the period of time during which the Service was not available. <br />
                                    11.2.        The Client acknowledges and agrees that Wexplore does not guarantee that the Services, including the Payment Services, will serve any specific purpose, specifically securing a job or any needs from the Client him/herself. Any form of explicit or implicit warranty is excluded where this does not contrast with the current norms. Neither Wexplore nor any of its licensees, employees, contractors or agents guarantee the suitability of the services object of the present contract to any specific purpose and/or guarantee to the User the securing of a job. Wexplore or whomever has participated to the realization or the delivery of the offered services, cannot be held accountable for any damage (whether direct or indirect) related to the application of said services or to the suspension and/or interruption of their functioning. In addition, because of the specific structure of the network, in which many entities are involved, no guarantee can be made as to the constant usability of the Service.  <br />
                                    11.3         Client assistance for the Service is managed as per indications provided on the Website, and is not operative 24/7. The Client shall in any case communicate to Wexplore in a timely manner, and in any case no later than 12 (twelve) hours following any irregularity or dysfunction in the Services. The Client, therefore, agrees that any damage caused by the delayed intervention from the Customer assistance may not be charged to Wexplore, and renounces here from now the claim to any reimbursement and/or compensation. </p>
                                  <p><strong>12)           Services modifications and changes in the offer conditions:</strong><br />
                                    12.1         The Client acknowledges and accepts that the Services object of the present contract are based on continuously evolving technology; for this reason Wexplore retains the right to change the technical features of the Services and vary the offer conditions in any moment and without notice, whenever this will be made necessary by technological evolution and by organizational and/or delivery necessities. It is understood that contracts finalized prior to the changes or variations will be fully accepted and, the agreed conditions will be respected. <br />
                                    12.2         Should Wexplore modify the present General Conditions, said changes will be communicated to the Client via e-mail or publication on the Website. Said changes will be effective 30 (thirty) days from the date of communication. Within this period, the Client may exercise the right to terminate the contract via certified electronic e-mail at the address <a href="mailto:adivalue@pec.it">adivalue@pec.it</a>, or through recorder delivery mail addressed to Wexplore Sas, Via Sangallo, 33 20133 Milan, Italy. Should the Client fail to exercise the right of termination in the ways and terms described above, the variations will be then understood to be acknowledged and accepted. <br />
                                    12.3.        Wexplore claims the right, to its unquestionable opinion, to modify the system&rsquo;s functionalities and structure. Wexplore cannot be held accountable for any direct or indirect damage resulting from the activation and/or interruption of the service, and of any additional services. </p>
                                  <p><strong>13)           Subcontracting:</strong><br />
                                    The Client may not transfer the contract, whether partly or in its entirety, to a Third Party, and neither the rights and/or obligations thereof. The Client herewith agrees, pursuant to art. 142 of the Civil Code, that Wexplore may transfer to Third Parties the Contract, whether partly on in its entirety, including the rights and/or obligations thereof. </p>
                                  <p><strong>14)           Industrial and/or intellectual property rights – downloadable contents:</strong><br />
                                    14.1.        Wexplore authorizes the Client to view and download the material available on the Website, exclusively for a personal and non commercial use, and exclusively for the purpose related to the present contract, considering that Wexplore remains the sole owner of all intellectual and industrial property rights of any kind, whether Italian or International. In any case, the Client is forbidden to make any use of the material contained on the Website other than those stated above, including publishing it and/or spreading it under the Client&rsquo;s name. <br />
                                    14.2.        Any material constituting industrial and/or intellectual property of Third Parties and that is made available to Clients through the deliver of the Service(s) must be used by the Client in compliance with those same rights. The Client takes full responsibility on this, and releases Wexplore now and then from any liability or indemnification of any prejudicial consequences deriving from the improper use of said property. <br />
                                    14.3.        Should the Client violate Wexplore and/or Third Parties&rsquo; industrial or intellectual property rights, Wexplore will rightfully terminate the contract with the Client. &nbsp; </p>
                                  <p><strong>15) Limitation of liability:</strong> <br />
                                    <a name="11.1" id="11.1"></a>15.1.        The Client takes full responsibility for all his/her activities related to the Services offered by Wexplore, and releases Wexplore from any liability, claim, or threat related to or deriving from the use or abuse of the Service and/or of the information provided through the Service itself. <br />
                                    <a name="11.2" id="11.2"></a>15.2         The Client warrants that he/she will use Wexplore&rsquo;s Services exclusively for legitimate and law-abiding purposes, compliant to norms, regulations, and customs.  <a name="11.3" id="11.3"></a><br />
                                    15.3         The Client takes full responsibility for all download operations that he/she should perform during the use of the Service and/or of the material uploaded in the Blog. <br />
  <a name="11.4" id="11.4"></a>15.4.        The Client is fully responsible and liable for the web contents available to him/her on the Blog. In uploading such contents, the Client agrees to the present General Conditions. <a name="11.5" id="11.5"></a><br />
                                    15.5.        Should Wexplore be subject to any legal action from third parties related to its activities or to the use of the Service by a Client, the same Client agrees to release Wexplore from any liability, claim, action or prejudicial effect connected to said legal actions; the Client further agrees to reimburse every expense and any direct and/or indirect damage suffered by Wexplore from the said legal actions.  <a name="11.6" id="11.6"></a><br />
                                    15.6.        The Client further agrees to release Wexplore from any liability, and subsequent losses, damages, costs, and expenses suffered and/or incurred by third parties and deriving from a use of the Website that is not compliant to the present General Conditions, where these violations have been committed by third parties the Client has allowed to use the Website. This includes any legal fees Wexplore should incur, including damages claimed by third parties for whatever reason.  <br />
                                    15.7.        The Client takes full responsibility for every claim or prejudice deriving to him/herself or to others from the sharing, stealing, and transmitting to unauthorized third parties the material inserted in the Blog by the Client him/herself or by a third party. <a name="11.8" id="11.8"></a><br />
                                    15.8.        Wexplore declares that it does not perform an editorial review of the Blog contents: any responsibility for any offense or damage deriving from such contents is to be attributed exclusively to the Clients. <a name="12" id="12"></a><a name="13" id="13"></a></p>
                                  <p><strong>16)           Service Suspension</strong><a name="13.1" id="13.1"></a>:<br />
                                    16.1.        Wexplore has the right to temporarily suspend the delivery of the Service without advance notice, for the time strictly necessary to perform necessary and/or opportune technical interventions to improve the quality of said Service. <a name="13.2" id="13.2"></a><br />
                                    16.2.        Wexplore may interrupt the delivery of the Service in any moment for founded security reasons or violations of confidentiality, giving communication of such an occurrence to the Client.  <a name="13.3" id="13.3"></a><br />
                                    16.3         Furthermore Wexplore has the right to immediately and definitely interrupt the delivery of the Service to Client who, upon verification, shall prove to have violated the dispositions concerning his/her obligations. </p>
                                  <p><strong>17)           Client Data:</strong><br />
                                    17.1         The Client agrees to communicate to Wexplore his/her personal data as necessary for the correct delivery and execution of the contract in its entirety; Client warrants under his/her personal and full responsibility, that said data are correct, true, and updated and that allow to ascertain his/her real identity. The Client agrees to communicate to Wexplore any change in the provided data in a timely manner, and in any case no later than 15 (fifteen) days later than said change as indicated on the Website, as well as to provide in any moment, on behest of Wexplore, adequate proof of his/her identity, domicile or residency, or if applicable of their qualification as legal representative of the juridical entity having required the Service. Upon receiving said communication, Wexplore may ask the Client any additional documentation as it shall see fit to prove the communicated changes. Should the Client fail to provide said communication or the required documentation, or should the Client provide date which shall prove false, inaccurate or incomplete, or that Wexplore shall consider as such based on its unquestionable judgment, Wexplore shall have the right to: <br />
                                    a) refuse the request submitted by the Client and referring to any operations related to a Service; <br />
                                    b) suspend indefinitely and without notice the services effective immediately;<br />
                                    c) cancel and/or interrupt without further notice any operation of changes of data associated to the Service;<br />
                                    d) terminate the contract withholding as penalty the amount paid by the Client. Wexplore may furthermore claim the right to ask for additional compensation as a result of the incurred damage, and the Client may not raise any claim towards Wexplore related to reimbursement, indemnification and/or other forms of compensation for the amount of time he/she may not have used the Service. </p>
                                  <p><strong>18)           Limitation of liability of Wexplore</strong><br />
                                    18.1         The Client acknowledges and agrees that the upload of information and their diffusion on the web through Wexplore&rsquo;s Services are entirely at his/her own risk. The Client agrees that the internet is not controlled by Wexplore and that, due to its specific structure, no public or private entity, including Wexplore, is able to guarantee and monitor the internet&rsquo;s performance and functionalities, and neither to control the content of the information that are transferred through its own network. For this reason the Client further agrees that no responsibility may be attributed to Wexplore for the transmission or receipt of any illegal information. The Client accepts to hold Wexplore harmless from any action of third parties related to violations of national or international laws carried out by the Client. <br />
                                    18.2.        Wexplore cannot be held accountable, in any case, for the information, data and contents uploaded or conveyed or treated in whatever way by the Client through the Service and in general for the use the Client shall make of the Service. Wexplore claims the right to adopt any measure or action to protect its rights and interests, including communicating to the authorities the data that will allow to identify the Client. Wexplore cannot be held accountable should the delivery of the Service, as per the precise specifications required by the Client, be conditioned by a third party (including but not limited to: a partner or provider of Wexplore). The Client therefore acknowledges and agrees that Wexplore is not liable in any way for any damages incurred by the Client him/herself and/or third parties, whether directly or indirectly, following the use of the provided Services. <br />
                                    18.3 The Client holds Wexplore harmless for now and then, and acknowledges and agrees the following: <br />
                                    a) the use of services delivered in cooperation with other infrastructures (national and international) is limited to the boundaries and norms established by the same service providers, as well as by the effective legislation in the Countries that host such services, and by any applicable international legislation; <br />
                                    b) technical interruptions of the services are possible due to breakdowns and malfunctioning of machines and software, be they owned by Wexplore or by its providers; <br />
                                    c) the very nature of online services, in which multiple entities are involved, does not allow to provide any warranty as to the constant accessibility of the Service and/or the possibility to access any web space worldwide and/or the sending and receipt of information; <br />
                                    18.4         Wexplore commits to ensure the best possible functionality of the system, while not being responsible for delays, malfunctioning, suspension and/or interruption of the Service delivery determined by causes outside of its reasonable control, including but not limited to: <br />
                                    a) accidents, acts of God or force majeur; <br />
                                    b) action by a third party (including but not limited to: unauthorized publication by others of the contents uploaded by the Client in any area); <br />
                                    c) malfunctioning or non-conformity of the connectivity devices used or owned by the Client; <br />
                                    d) tampering or interventions on the services or devices performed by the Client or by Third parties not expressly authorized by Wexplore;  <br />
                                    e) improper or erroneous use of the Service by the Clients per the present General Conditions or the indications contained on the Website;<br />
                                    f) breakdown or malfunctioning of the machines and software, be they owned by Wexplore or by its providers.<br />
                                    The Parties accept that in such cases, Wexplore will not be held liable of any loss, damage or injury experienced or to be experienced by the Client and/or by Third parties, whether direct or indirect, foreseeable or unforeseeable, including but not limited to: economic/financial losses, business or profit losses, losses related to venture start-up; the Client therefore acknowledges and agrees that it shall have no right to put forward any claim to indemnity, compensation, reimbursement of any kind. </p>
                                  <p><strong>19)           Confidentiality:</strong><br />
                                    19.1.        Wexplore and the Client both agree to treat as confidential any data or information made known or managed in relation to the activities related to the delivery of the Service through the Website. </p>
                                  <p><strong>20)           Express termination clause:</strong><br />
                                    20.1.        The present contract will be rightfully terminated pursuant to art. 1456 of the Italian Civil Code should the Client: </p>
                                  <ol>
                                    <li>cede the contract or a part thereof to others; </li>
                                  </ol>
                                  <p><em>b)              </em>be insolvent or not compliant towards Wexplore, also for services not subject of the present contract; <br />
                                    <em>c)</em>              fail to complete the payment for the due amount, and the Service has been in the meanwhile activated, waiving the provisions of the present General Conditions; <br />
                                    <em>d)              </em>use the Services differently than as maintained by the present General Conditions; <br />
                                    <em>e)              </em>violate the dispositions of Artt. 10 and 16 of the present Conditions.  <br />
                                    20.2.        Upon the termination, Wexplore will be authorized to interrupt the access to the Service without further notice. In such a case, the Client acknowledges and agrees that the amount paid by the Client will be held by Wexplore as a penalty, notwithstanding the reimbursement of any additional damages; conversely the Client may not put forward any claim to reimbursement, compensation and/or reparation for damages for the time in which he/she has not accessed the Service. <br />
                                    It is agreed that said express termination clause does not affect the other termination options, and in general the other protective measures provided for by the current legislation.</p>
                                  <p><strong>21)           Final provisions and communications: </strong><br />
                                    21.1. The present Contract shall supersede all previous communications, representations, or understanding between the Parties, and shall constitute the entire agreement between the Parties. <br />
                                    21.2.        No amendments or other variations to the present Contract shall be effective unless expressly approved in writing by both Parties. <br />
                                    21.3.        In no case whatsoever any Client default and/or behavior not compliant to the present Conditions shall be considered as waivers of said Conditions or implicit acceptance of such defaults, even when Wexplore shall choose to not contest them. Any failure from Wexplore to exercise or enforce any of its rights or clauses under the present Contract, shall not constitute a waiver of said rights or clauses. <br />
                                    21.4.        All communications to the Client related to the present Contract may be performed by Wexplore either via email (both certified or not), via tracking delivery system, or via fax to the contact details indicated by the Client upon the Registration phases. Therefore, Wexplore shall consider the Client as aware of said communications. Any variation in the Client&rsquo;s contact details that is not communicated to Wexplore shall not constitute an objection element. Every communication that the Client means to send to Wexplore related to the present contract shall have to be sent to the contact details indicated on the Website.  <br />
                                    21.5.        If any provision of these General Conditions is determined to be unenforceable or invalid, whether wholly or partly, the remaining provisions of these Conditions shall remain in full force and effect. <br />
                                    21.6.        For anything not expressly provided for in the present General Conditions, the Parties submit to the effective legislation at the time in which the contract is finalized, insofar as such legal provisions are compatible with the matter at hand. </p>
                                  <p><strong>22)           Governing law, Jurisdiction, and Dispute resolution</strong> <strong> </strong><br />
                                    22.1         The present General Conditions are governed by and shall be construed in accordance with the internal laws of Italy. For any claim or controversy related to the interpretation, execution, and termination of the present Contract, the Parties submit to the exclusive jurisdiction of the relevant courts in Milan; the sole exception shall be that in which the Client shall have finalized the present contract as Consumer, for purposes not related to his/her professional or entrepreneurial activity; in such cases, the Parties shall submit to the exclusive jurisdiction of the place of residence of the Client, if located on the territories of the State of Italy. </p>
                                  <p><strong>Restrictive Clauses</strong><strong> </strong><br />
                                    Pursuant to the artt. 1341 and 1342 of the Italian Civil Code, the Client expressly acknowledges and agrees to the following clauses, after having thoroughly examined them: <br />
                                    2)              Registration to the Website and finalization of the Services delivery contract for Services reserved to Users and Payment Services; <br />
                                    4)              Registration Policy;<br />
                                    5)              Characteristics of the Services;<br />
                                    6)              Fees and Payment of Payment Services;<br />
                                    7)              Service activation and delivery;<br />
                                    8)              Duration, extension, termination, and cancellation of the Contract;<br />
                                    9)              Blog usage;<br />
                                    10)           Minors protection;<br />
                                    11)           Functionalities of the Services;<br />
                                    12)           Services modifications and changes in the offer conditions;<br />
                                    13)           Subcontracting;<br />
                                    14)           Industrial and/or intellectual property rights – downloadable contents; <br />
                                    15)           Limitation of Liability;<br />
                                    16)           Service Suspension;<br />
                                    17)           Client Data;<br />
                                    18)           Limitation of Liability of Wexplore;<br />
                                    20)           Express termination clause;<br />
                                    21)           Final provisions and communications; <br />
                                    22)           Governing law, Jurisdiction, and Dispute resolution.</p>
                                  <div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                    <div> </div>
                                  </div>
								</div></div></div></div></div></div></div></div>
