
	<div class="content_wrapper clearfix">
		<div class="sections_group">
			<div class="entry-content">
				<div class="section flv_sections_8" id="orientation-test">
					<div class="section_wrapper clearfix">
						<div class="items_group clearfix">
							<!-- Page Title-->
							<!-- One full width row-->
							<div class="column one column_fancy_heading">
								<div class="fancy_heading fancy_heading_icon">
									<h2 style="color:#54b141; background: url(/en/frontend/immagini/linea-titolo-verde.png) no-repeat bottom center; padding-bottom: 25px;">CONDIZIONI DI VENDITA</h2>
								</div>
							</div>
							<div class="column one column_column">
								<div class="column_attr ">
<p><strong>CONDIZIONI GENERALI DI CONTRATTO E TERMINI D’USO SERVIZI </strong><br>
  Il presente sito (di seguito il &quot;Sito&quot;) www.wexplore.co è di proprietà di Gielle Sas (di seguito &ldquo;Gielle&rdquo; o &ldquo;Wexplore&rdquo;) con sede legale in Via Sangallo, 33 20133 Milano codice fiscale ed iscrizione presso il Registro delle Imprese di Milano n. 32154841, P. IVA 07604310966.<br>
Gielle osserva la normativa in materia di contratti conclusi a distanza di cui agli art. 50 e seguenti del D.Lgs 206/2005.<br>
Ti invitiamo a leggere attentamente le condizioni sotto riportate, ed a stamparle e/o salvarle su altro supporto duraturo a tua scelta</p>
<p><strong>1. Oggetto:</strong><br>
  <strong>1.1. </strong>Le presenti Condizioni Generali di Contratto e Termini d&rsquo;Uso dei servizi (di seguito per brevità &ldquo;Condizioni generali) disciplinano le modalità ed i termini con cui Gielle fornisce il servizio  di consulenza (specificamente orientamento professionale) e formazione (di seguito i &quot;<strong><em>Servizi</em></strong>&quot; o il &quot;<strong><em>Servizio</em></strong>&quot;). Il Sito è accessibile anche ai non iscritti con riferimento all'elenco servizi offerti e prezzi, informazioni sull'azienda e lettura blog con contenuti (i &quot;<strong><em>Servizi accessibili a tutti</em></strong> &quot;). Tutti gli altri Servizi (i &quot;<strong><em>Servizi riservati agli Utenti</em></strong>&quot;) sono erogati esclusivamente agli Utenti registrati. I Servizi riservati agli Utenti possono essere gratuiti, ovvero a pagamento (i &quot;<strong><em>Servizi a Pagamento</em></strong>&quot;). Nell'erogazione dei Servizi, Wexplore si attiene al proprio Codice Etico Aziendale, reperibile al seguente link https://www.wexplore.co/it/codice-etico.<br>
  <strong>1.2. </strong>I Servizi sono offerti da Wexplore esclusivamente da remoto mediante la rete internet con le modalità descritte nello stato di fatto e di diritto in cui si trovano alla data della richiesta di attivazione/rinnovo, così come pubblicato sul Sito, con le caratteristiche tecniche ed economiche ivi descritte che il Cliente, accettando le seguenti Condizioni Generali, dichiara esplicitamente di conoscere ed accettare. L&rsquo;offerta e il contenuto dei Servizi sono indicati nell'apposita area sul Sito www.wexplore.co, fatta salva la facoltà di Gielle di sospenderli o revocarli in qualsiasi momento; in tal caso, i contratti conclusi prima della sospensione o della revoca saranno onorati alle condizioni pattuite. Eventuali ulteriori prestazioni rispetto a quelle stabilite nel Modulo potranno essere fornite da Gielle solo dopo specifica richiesta scritta del Cliente secondo modalità da definirsi di volta in volta.<br>
  <strong>1.3. </strong>Le presenti Condizioni Generali sono state redatte e predisposte in osservanza ed in conformità alle disposizioni contenute nel D.lgs. 206/2005 (Codice del Consumo) e nella L. 40/2007 (Misure urgenti per la tutela dei consumatori, la promozione della concorrenza, lo sviluppo di attività economiche e la nascita di nuove imprese); esse hanno portata di carattere generale e potranno subire le modifiche rese necessarie da successive disposizioni di legge e/o regolamenti.</p>
<p><strong>2. Registrazione al Sito e conclusione del contratto di fornitura dei Servizi Riservati agli Utenti e dei Servizi a Pagamento:</strong><br>
  2.1 Con la Registrazione al Sito, secondo le modalità di cui all'art. 4 che segue, l'Utente dichiara di accettare integralmente le presenti Condizioni Generali, nonché il contenuto dei documenti, delle norme, delle disposizioni e delle procedure da esse richiamate, rendendole vincolanti nei confronti dell'Utente anche prima della conclusione del singolo contratto di fornitura dei Servizi a Pagamento di cui al successivo art. 2.2.. <br>
  2.2 Il Contratto di fornitura dei Servizi Riservati agli Utenti, si conclude alla data del corretto e puntuale ricevimento da parte di Gielle del modulo d'ordine dello specifico Pacchetto, compilato ed accettato online dal Cliente in ogni sua parte sul sito https://www.wexplore.co con le procedure previste per la conclusione dei contratti online, unitamente al ricevimento via e-mail della conferma circa l&rsquo;intervenuto pagamento del corrispettivo per il tipo di servizio prescelto dal Cliente, rilasciata dal Soggetto individuato come competente ad effettuare tale operazione. Resta inteso che, in caso di Servizio a Pagamento, nessuna prestazione sarà erogata da Gielle in assenza del ricevimento del pagamento. Decorsi 90 (novanta) giorni dalla data dell&rsquo;ordine, in assenza di pagamento, l&rsquo;ordine sarà annullato e cancellato, senza alcun preavviso. Il Cliente prende atto ed accetta che, nell'ipotesi che precede, non potrà avanzare alcuna pretesa nei confronti di Gielle e la manleva, ora per allora, da qualsiasi responsabilità in riferimento all&rsquo;annullamento dell&rsquo;ordine. Le somme eventualmente ricevute in acconto da Gielle con riferimento ad un ordine annullato saranno messe a disposizione del Cliente con le modalità ed i termini indicati di seguito.</p>
<p><strong>3.Definizioni:</strong><br>
  3.1. I seguenti termini hanno il significato di seguito specificato: <br>
  <strong><em>Servizio:</em></strong> il servizio di consulenza (in particolare orientamento professionale) e formazione erogato tramite il Sito, come di seguito definito;<br>
  <strong><em>Sito:</em></strong> il sito web di Wexplore reperibile all'indirizzo www.wexplore.co; <br>
  <strong><em>Servizi accessibili a tutti:</em></strong> le pagine web del Sito accessibili a chiunque, anche in assenza di Registrazione;<br>
  <strong><em>Utente:</em></strong> ciascun soggetto che abbia concluso con successo la procedura di registrazione di seguito descritta, accettando le presenti Condizioni Generali ed assumendo i diritti e doveri ivi descritti.<br>
  <strong><em>Servizi riservati agli Utenti</em></strong>: servizi di consulenza e formazione erogati esclusivamente agli Utenti registrati al Sito, gratuiti o a pagamento, erogati attraverso specifici Pacchetti;<br>
  <strong><em>Servizi a Pagamento</em></strong>: Servizi riservati agli Utenti erogati a pagamento, contenuti negli specifici Pacchetti acquistabili sul Sito.<br>
  <strong><em>Pacchetti</em></strong>: specifici &quot;pacchetti&quot;, gratuiti o a pagamento, contenenti i Servizi e fruibili dagli Utenti registrati sul Sito.<br>
  <strong><em>Condizioni Generali</em></strong>: i termini e le condizioni del Contratto, che l'Utente accetta al momento della registrazione, cliccando sul pulsante &quot;Accetto&quot;.<br>
  <strong><em>Contratto:</em></strong> il contratto di fornitura dei Servizi Riservati agli Utenti, retto dalle Condizioni Generali, che viene concluso tra Gielle e ciascun Utente con le modalità di cui all'art. 2.2. che precede. Le Condizioni Generali saranno applicabili anche ai servizi che verranno forniti in futuro agli Utenti, salvo che venga altrimenti previsto all'atto della registrazione o della prima fornitura del nuovo servizio. Alcuni servizi, comunque regolati dalle Condizioni Generali, potrebbero essere soggetti anche a condizioni e termini particolari, in considerazione della loro natura e /o delle loro caratteristiche, che saranno comunicate agli Utenti con le modalità previste dalle Condizioni Generali. <a name="2"></a></p>
<p><strong>4. Modalità di registrazione</strong>:<br>
  4.1. L'accesso al Servizio è consentito solamente ad un Utente registrato mediante un termine identificativo (indirizzo e-mail) ed una parola chiave (password). All'atto della registrazione sul Sito, l'Utente è tenuto ad indicare i propri dati anagrafici. Sarà richiesto all'Utente di indicare le modalità di pagamento al momento della la conclusione di eventuali Contratti di fornitura di Servizi a Pagamento.<br>
  La Registrazione è consentita sia a persone fisiche (purché  maggiorenni) sia a persone giuridiche.<br>
  4.2. L'Utente ha diritto di modificare la password seguendo le istruzioni presenti nel Sito, e riconosce che l'indirizzo e-mail fornito e password costituiscono il sistema di validazione degli accessi dell'Utente al Sito ed il solo mezzo idoneo a legittimare l'Utente ad accedere al Sito. L'Utente assume pertanto la responsabilità di tutti gli atti compiuti mediante utilizzo di nickname e password ad esso attribuiti. L'Utente è tenuto a conservare nickname e password nella massima riservatezza e a custodirli con la massima diligenza. <br>
  4.3. L'Utente si impegna a comunicare nel minor tempo possibile a Gielle per iscritto, a mezzo di lettera raccomandata con avviso di ricevimento all'indirizzo Via Sangallo 33, 20133 Milano, Italia, ovvero via mail all'indirizzo info@wexplore.co (purché seguito entro 48 ore dall'invio di lettera raccomandata a/r), i) qualsiasi uso non autorizzato di nickname e password ad esso attribuite, ii) ogni altra violazione della sicurezza relativa al Sito o al profilo Utente di cui venisse a conoscenza. Gielle si obbliga, a seguito della comunicazione, a disattivare la password oggetto della violazione di segretezza. <br>
  4.4. All'atto della compilazione del modulo di registrazione sono richiesti all'Utente alcuni dati personali, il cui trattamento avviene secondo quanto previsto dal D. Lgs. 196/2003 (Codice della Privacy) e in conformità all'informativa all'Utente di cui alla procedura di registrazione, consultabile in ogni caso al seguente link https://www.wexplore.co/it/informativa-privacy<br>
  . Con l'accettazione delle Condizioni Generali, l'Utente dichiara che i propri dati sono aggiornati, corretti e veritieri, e si impegna a modificarli tempestivamente affinché siano costantemente aggiornati, completi e veritieri. </p>
<p><strong>5. Caratteristiche dei Servizi:</strong><br>
  <a name="2.1"></a>5.1.Tutti i Servizi Riservati agli Utenti sono erogati esclusivamente agli Utenti registrati, con le seguenti modalità: <br>
  - self service on line: documenti scaricabili in formato .pdf, questionari on line da compilare, video ecc.;<br>
  - video chat con consulente<a name="2.2"></a>, video chat singole o di gruppo con Consulente;<br>
  - utilizzo blog con contenuti (con possibilità di interazione).<br>
  5.2. I Servizi Riservati agli Utenti, con le modalità che precedono, sono contenuti negli specifici Pacchetti acquistabili dall'Utente attraverso il Sito.<br>
  5.3. I Pacchetti che contengono i Servizi sono ordinati dagli Utenti registrati secondo le modalità dell'articolo 2.2. che precede e possono essere gratuiti o a pagamento.<br>
  5.4. <a name="2.3"></a>I Servizi accessibili a tutti, anche in assenza di registrazione e sono costituiti da:<br>
  - pagine informative su servizi offerti e prezzi;<br>
  - informazioni sull'azienda;<br>
  - blog con contenuti (solo lettura).</p>
<p><strong>6. Corrispettivi e modalità di pagamento dei Servizi a Pagamento:</strong><br>
  6.1. Il pagamento del corrispettivo relativo allo specifico Pacchetto ordinato, qualora relativo a Servizi a Pagamento, deve essere eseguito dall'Utente contestualmente o all&rsquo;inoltro online del singolo ordine e, comunque, anticipatamente all'attivazione del Servizio. Il prezzo del Servizio è individuato in base alle tariffe in vigore al momento dell&rsquo;ordine ed indicate alla pagina web www.wexplore.co e si differenzia a seconda del Pacchetto ordinato dal Cliente.<br>
  6.2. A tutti gli importi fatturati sarà applicata l&rsquo;Iva, se dovuta, la quale, assieme a qualsiasi altro onere fiscale derivante dall&rsquo;esecuzione del contratto, sarà a carico dell'Utente. In ogni caso, l'Utente dichiara espressamente di sollevare ora per allora Gielle da ogni e qualsiasi responsabilità derivante dalle transazioni o dai pagamenti effettuati. <br>
  6.3. Ai sensi e per gli effetti di quanto previsto dall'art. 52 comma 1 lett. e) D.lgs. 206/2005, il Cliente prende atto ed accetta che il pagamento del corrispettivo per il Servizio prescelto potrà essere effettuato con una delle modalità indicate sul sito www.wexplore.co, nell&rsquo;apposita sezione dedicata all&rsquo;argomento. <br>
  6.4. Il Cliente non potrà far valere diritti o sollevare eccezioni di alcun tipo se prima non avrà provveduto ad eseguire correttamente i pagamenti previsti dal Contratto ed a fornirne apposita prova documentale su richiesta di Gielle. Nel caso in cui il pagamento del prezzo non risulti valido o sia per qualsiasi motivo revocato o annullato dal Cliente, oppure non sia eseguito, confermato o accreditato a beneficio della stessa Gielle, quest&rsquo;ultima si riserva la facoltà di sospendere e/o interrompere l&rsquo;attivazione e/o la fornitura del Servizio con effetto immediato, qualora lo stesso sia già stato attivato, rimanendo in capo alla persona che ha ordinato la registrazione l'obbligo del pagamento e degli interessi di legge relativi al ritardo. <br>
  6.5 Con l&rsquo;accettazione delle presenti Condizioni Generali, il Cliente acconsente espressamente che la fattura gli possa essere trasmessa e/o messa a disposizione in formato elettronico. <br>
  6.6. I crediti eventualmente esistenti in favore del Cliente, a qualsiasi titolo, e non imputati ad alcun Servizio e/o Pacchetto, per qualsiasi ragione, dovranno essere utilizzati da quest&rsquo;ultimo per l&rsquo;acquisto o il rinnovo di Servizi erogati da Gielle entro e non oltre il periodo di 12 (dodici) mesi dalla data del pagamento, con le modalità indicate sul sito www.wexplore.co. Trascorso inutilmente il periodo di tempo sopra indicato, senza che il Cliente abbia utilizzato il predetto credito, questo si intenderà definitivamente acquisito ed incassato da parte di Gielle ed il Cliente non potrà pretenderne la restituzione o la sua utilizzazione.</p>
<p><strong>7. Attivazione ed erogazione del servizio:</strong><br>
  7.1. Il Cliente prende atto ed accetta che le pratiche di attivazione o eventuale, ove e se previsto, rinnovo del Servizio avranno inizio al momento della conclusione del Contratto relativo allo specifico Pacchetto ordinato dall'Utente. Gielle comunicherà al Cliente tramite e.mail, l&rsquo;attivazione del Servizio. Con l&rsquo;attivazione del Servizio, tutti i relativi diritti di utilizzazione si trasferiranno in favore del Cliente, il quale sarà ritenuto il legittimo titolare del Servizio restandone, altresì, l'unico ed esclusivo responsabile per il suo utilizzo, nonché per il materiale ed i dati, anche personali, eventualmente da Egli trattati mediante il Servizio medesimo.<br>
  7.2. Gielle si riserva la facoltà di non procedere all&rsquo;attivazione o al rinnovo del Pacchetto, a suo insindacabile giudizio, nei casi in cui:<br>
  <strong>a)</strong> il Cliente risulti essere stato inadempiente nei confronti di Gielle, anche in relazione a precedenti rapporti contrattuali. In tal caso, l&rsquo;attivazione del Servizio potrà essere subordinata, a discrezione ed a seguito di comunicazione di Gielle, al previo adempimento del rapporto precedente;<br>
  <strong>b)</strong> il Cliente non fornisca a Gielle la documentazione dalla medesima richiesta, o comunque fornisca dati falsi o che Gielle sospetti essere tali; <br>
  <strong>c)</strong> il Cliente risulti iscritto nel registro dei protesti o assoggettato a procedure esecutive;<br>
  <strong>d)</strong> il Cliente sia ammesso o sottoposto a procedure concorsuali; <br>
  <strong>e)</strong> esistano motivi tecnici, organizzativi o di altra natura che siano di ostacolo all&rsquo;attivazione del Servizio.<br>
  Gielle provvederà a comunicare al Cliente la mancata attivazione o il mancato rinnovo del Pacchetto, senza doverne indicare i motivi, e sarà tenuta esclusivamente a restituire al Cliente il corrispettivo che risulti essere stato dalla medesima eventualmente ricevuto in pagamento, senza ulteriori oneri. Resta inteso che su tale somma non saranno dovuti interessi di alcun genere. Il Cliente prende atto ed accetta di aver diritto esclusivamente alla restituzione del prezzo pagato a Gielle e di non poter avanzare nei confronti di Gielle alcuna richiesta di indennizzo, di risarcimento del danno o pretesa di alcun genere a causa della mancata attivazione del Servizio. <a name="3"></a><br>
  7.3. A seguito dell'attivazione del Servizio di cui al Pacchetto ordinato, il Cliente potrà fruire del Servizio attraverso l&rsquo;apposita area riservata del sito, inserendo le proprie credenziali di accesso (username e password). Ogni pagina dell'area riservata contiene le &quot;istruzioni per l'uso&quot; della stessa.</p>
<p><strong>8. Durata, rinnovo, cessazione, recesso del contratto:</strong><br>
  8.1. Il Contratto di fornitura dei Servizi a Pagamento avrà una durata pari al periodo di tempo relativo allo specifico Pacchetto acquistato, con decorrenza dalla data di attivazione del Servizio. <br>
  All&rsquo;approssimarsi della data di scadenza Gielle, a mero titolo di cortesia e quindi senza che così facendo assuma alcuna obbligazione nei confronti del Cliente, avrà la facoltà di inviare alle caselle di posta elettronica di riferimento avvisi di prossima scadenza e di conseguente cessazione del servizio in caso di mancato rinnovo, ove previsto.<br>
  8.2. Alla data di scadenza fissata per il Pacchetto prescelto, il Servizio e gli eventuali Servizi aggiuntivi saranno disattivati ed il Contratto cesserà di avere efficacia, salvo rinnovo, ove previsto, alle tariffe ed alle condizioni contrattuali in vigore al momento del rinnovo. <br>
  8.3. L'Utente che sia Consumatore ai sensi del Codice del Consumo avrà facoltà di recedere liberamente dal Contratto entro quattordici giorni lavorativi successivi alla sua conclusione. Il recesso dovrà essere comunicato a mezzo lettera raccomandata con avviso di ricevimento inviata a Gielle. Il recesso potrà essere inviato anche, nello stesso termine, a mezzo posta elettronica all'indirizzo e-mail info@wexplore.co a condizione che la comunicazione di recesso sia confermata a mezzo lettera raccomandata con avviso di ricevimento entro le 48 ore successive. <a name="4"></a>Nello specifico caso in cui la prestazione a carico di Gielle di cui allo specifico Pacchetto acquistato dall'Utente, sia completamente esaurita, è escluso il diritto di recesso a carico del Consumatore, ai sensi dell'articolo 59 Codice del Consumo. Ai sensi del medesimo articolo 59, l'Utente autorizza sin d'ora l'inizio anticipato della prestazione e accetta espressamente la perdita del diritto di recesso a seguito della piena esecuzione del contratto da parte di Gielle.</p>
<p><strong>9. Utilizzo dei blog</strong>.<br>
  <a name="4.1"></a>9.1. Con la Registrazione al Sito ai sensi dell'articolo 4 che precede, ciascun Utente avrà facoltà di commentare, identificato con il proprio Username, i Blog contenuti sul Sito, relativi ad argomenti connessi al Servizio.<br>
  9.2. Non è consentito all'Utente pubblicare sui Blog materiale pornografico, osceno o illegale, a titolo esemplificativo ma non esaustivo: software pirata, cracks, warez, malware, virus, siti di phishing (fake login), mp3 che violino la normativa sul diritto d'autore, materiale che possa cagionare danno a terzi. <a name="4.2"></a><br>
  9.2. L'Utente registrato dichiara inoltre di assumersi la piena e totale responsabilità giuridica nei confronti di quanto pubblicato quale commento ai Blog, manlevando e tenendo indenne Gielle da qualsiasi rivendicazione o pretesa derivante dall'uso o abuso dei servizi offerti. <a name="4.3"></a><br>
  9.3. L'Utente prende atto che Gielle si riserva il diritto di accedere, in ogni momento e senza preavviso, a sua discrezione, ai commenti dei Blog per verificare il rispetto delle Condizioni Generali. Gielle si riserva il diritto di sospendere immediatamente il Servizio qualora, a suo insindacabile giudizio, anche su segnalazione di terzi, ritenga siano state violate le presenti Condizioni Generali. L'Utente prende atto che Gielle, in adempimento ai propri obblighi derivanti da norme inderogabili di legge, possa consegnare il materiale immesso nei Blog e/o rivelarne il contenuto alle competenti autorità. Gielle è espressamente autorizzata ad inserire nel Sito ogni opportuna avvertenza circa l'inesistenza di qualsiasi collegamento tra Gielle e l'Utente o l'attività dallo stesso esercitata tramite i Blog. <a name="4.4"></a><a name="4.9"></a><a name="5"></a><a name="5.1"></a><br>
  9.4. L'Utente garantisce l'originalità di ogni informazione, programma, dato immesso tramite il Servizio sotto qualunque forma, in qualsiasi area o spazio messi a disposizione da Gielle. <a name="5.2"></a><br>
  9.5. Eventuale materiale protetto da copyright di terzi può essere utilizzato solo qualora l'Utente abbia acquisito, dal titolare del diritto d'autore, i connessi diritti di utilizzazione, quindi solo con il permesso scritto del titolare del diritto e con l'obbligo di citare la fonte e l'esistenza del permesso. Il materiale fotografico, audio o video di terzi o riproducente il ritratto di terzi può essere utilizzato solo qualora l'Utente abbia acquisito il consenso dell'autore e del soggetto ritratto. In relazione alla disponibilità di tali diritti e consensi l'Utente si assume ogni responsabilità esonerando completamente Gielle. <br>
  <a name="5.3"></a>9.6. L'Utente assume, inoltre, la piena responsabilità circa l'esattezza e veridicità del materiale immesso nei Blog, in nome proprio e/o per conto di terzi, e assicura che lo stesso è nella sua legittima disponibilità, non è contrario a norme imperative e non viola alcun segno distintivo, diritto di proprietà intellettuale, industriale, diritto di immagine o altro diritto di terzi derivante dalle norme giuridiche vigenti o dalle consuetudini o dagli usi. In ogni caso il Materiale immesso non deve presentare forme e/o contenuti a carattere pedo-pornografico, pornografico, osceno, blasfemo o diffamatorio. </p>
<p><strong>10.</strong> <strong>Tutela minori</strong>:<br>
  10.1. I minori non possono portare a termine la procedura d'iscrizione nemmeno con l&rsquo;assistenza di un genitore o tutore legale. <br>
  10.2. I soggetti che, esercitando potestà parentale sui minori, consentano loro l'uso del Servizio si rendono responsabili del comportamento on line del minore, del controllo dell'accesso e delle conseguenze in caso di abuso del Servizio da parte del minore. </p>
<p><strong>11. Funzionalità dei Servizi:</strong><br>
  11.1. I Servizi accessibili a tutti e i Servizi riservati agli Utenti contenuti nei Pacchetti ordinati dall'Utente, saranno di norma disponibili 24 (ventiquattro) ore su 24 (ventiquattro); tuttavia, il Cliente prende atto ed accetta che Gielle potrà sospendere e/o interrompere la loro fornitura per consentire l&rsquo;esecuzione di interventi di manutenzione ordinaria o straordinaria che si rendano opportuni e/o necessari sia ai locali della Server Farm, che ai server e/o apparecchiature ivi contenute.<br>
  In tali casi, Gielle si impegna ad eseguire i predetti interventi nel minor tempo possibile ed a ripristinare i Servizi quanto prima al fine di ridurre il disagio creato al Cliente. Il Cliente prende atto ed accetta che non potrà avanzare alcuna richiesta di indennizzo, rimborso o risarcimento nei confronti di Gielle per il periodo di tempo in cui non ha potuto usufruire dei Servizi. <br>
  11.2. Il Cliente prende atto ed accetta che Gielle non garantisce che i Servizi, ivi inclusi i Servizi a Pagamento, si adattino a scopi particolari, ovvero al reperimento di un posto di lavoro o comunque alle esigenze del Cliente medesimo. E&rsquo; espressamente esclusa ogni forma di garanzia esplicita od implicita, nella misura in cui ciò non contrasti con le norme vigenti. Né Gielle né alcuno dei propri licenziatari, dipendenti, collaboratori o agenti garantiscono l'idoneità dei servizi, oggetto del presente contratto, ad alcuna funzione specifica e/o garantiscono all'Utente il reperimento di un posto di lavoro. Gielle o chiunque abbia partecipato alla realizzazione ed alla fornitura dei servizi in parola, non può essere ritenuta responsabile per alcun danno (diretto o indiretto) connesso all'impiego dei servizi offerti o alla sospensione e/o interruzione del funzionamento dei medesimi. Inoltre, per la struttura specifica della rete, in cui molte entità sono coinvolte, nessuna garanzia può essere data sulla costante fruibilità del Servizio. <br>
  11.3. L'assistenza clienti per il Servizio è svolta secondo le modalità indicate sul sito www.wexplore.co nell'apposita sezione e non è garantita 24 ore su 24. Il Cliente si impegna comunque a comunicare a Gielle immediatamente o comunque non oltre le 12 (dodici) ore solari successive eventuali irregolarità o disfunzioni nei Servizi. Il Cliente, pertanto, prende atto che eventuali danni connessi al tardivo intervento dell'assistenza clienti non potranno comunque essere addebitati a Gielle, rinunciando sin d'ora a richiedere qualsiasi somma a Gielle a titolo di risarcimento e/o indennizzo.</p>
<p><strong>12. Modifiche dei servizi e variazioni alle condizioni dell'offerta:</strong><br>
  12.1. Il Cliente prende atto ed accetta che i Servizi oggetto del presente contratto sono caratterizzati da tecnologia in continua evoluzione, per questi motivi Gielle si riserva il diritto di modificare le caratteristiche tecniche del Servizio e di variare le condizioni dell'offerta in qualsiasi momento e senza preavviso, quando ciò sia reso necessario dall&rsquo;evoluzione tecnologica e da esigenze di fornitura e/o organizzazione. Resta inteso che i contratti conclusi anteriormente all'inserimento delle modifiche o variazioni saranno comunque accettati e rispettati integralmente alle condizioni pattuite.<br>
  12.2. Qualora Gielle modifichi le presenti Condizioni Generali, dette modifiche saranno comunicate al Cliente mediante e-mail o pubblicazione sul sito www.wexplore.co. Le predette modifiche avranno effetto decorsi 30 (trenta) giorni dalla data della loro comunicazione. Nello stesso termine il Cliente potrà esercitare la facoltà di recedere dal contratto con comunicazione scritta inviata a mezzo posta elettronica certificata (PEC) all&rsquo;indirizzo adivalue@pec.it, ovvero tramite raccomandata a.r. a Gielle Sas Via Sangallo 33, 20133 Milano, Italia. In mancanza di esercizio della facoltà di recesso da parte del Cliente, nei termini e nei modi sopra indicati, le variazioni si intenderanno da questi definitivamente conosciute ed accettate.<br>
  12.3. Gielle si riserva, a suo insindacabile giudizio, il diritto di modificare la funzionalità del proprio sistema, così come di modificarne la struttura. Gielle non potrà essere ritenuta responsabile per qualsivoglia danno, diretto od indiretto derivante dalla attivazione e/o interruzione del servizio e di eventuali servizi aggiuntivi. </p>
<p><strong>13. Cessione del Contratto:</strong><br>
  Il Cliente non potrà trasferire a Terzi, in tutto o in parte, il contratto, né i diritti e/o gli obblighi da esso scaturenti. Il Cliente presta sin d&rsquo;ora, ai sensi dell&rsquo;art. 1407 c.c., il proprio consenso affinché Gielle possa cedere a Terzi il Contratto e/o trasferire a Terzi, in tutto o in parte, i propri diritti e/o gli obblighi derivanti dal Contratto. <strong></strong></p>
<p><strong>14. Diritti di proprietà industriale e/o intellettuale – contenuti scaricabili:</strong><br>
  14.1. Gielle autorizza il Cliente a prendere visione e ad effettuare il download del materiale disponibile sul Sito, ad esclusivo uso personale ed a fini non commerciali, esclusivamente connessi all'oggetto del presente contratto, considerato che Gielle è titolare esclusiva di tutti i diritti di proprietà intellettuali ed industriali sia italiani che internazionali di qualsiasi natura. Ad ogni modo, è fatto divieto al Cliente di utilizzare il materiale contenuto nel sito per finalità diverse da quelle sopra indicate, nonché di pubblicarlo e/o diffonderlo a nome del Cliente.<br>
  14.2. Qualsiasi materiale che formi oggetto di diritti di proprietà intellettuale e/o industriale in favore di Terzi e che sia messo a disposizione del Cliente tramite la fornitura del Servizio, dovrà essere da questi utilizzato nel rispetto di tali diritti. Il Cliente assume ogni responsabilità in proposito, e si impegna a manlevare ed a tenere indenne, ora per allora, Gielle da qualsiasi conseguenza pregiudizievole che dovesse derivare ad un utilizzo non conforme alle disposizioni sopra indicate.<br>
  14.3. Nel caso in cui il Cliente violi i diritti di proprietà industriale o intellettuale di Gielle e/o di Terzi, Gielle si riserva il diritto di risolvere il contratto.</p>
<p><a name="6"></a><strong>15. Limitazione della responsabilità</strong>:<br>
  <a name="11.1"></a>15.1. Il Cliente assume esclusiva responsabilità per ogni sua attività nell'ambito dei Servizi offerti da Gielle e si impegna a manlevare e tenere indenne la stessa da qualsiasi rivendicazione, pretesa o minaccia relativa a o derivante dall'uso o dall'abuso del Servizio e/o delle informazioni che gli verranno fornite tramite il Servizio stesso. <br>
  <a name="11.2"></a>15.2. Il Cliente si obbliga a servirsi di Gielle esclusivamente per scopi leciti e conformi alla legge, ai regolamenti, agli usi ed alle consuetudini. <a name="11.3"></a><br>
  15.3. Il Cliente si assume ogni e più ampia responsabilità per le operazioni di download che dovesse compiere utilizzando il Servizio e del materiale oggetto di upload nei Blog. <br>
  <a name="11.4"></a>15.4. Il Cliente è responsabile e perseguibile legalmente in relazione ai contenuti dello spazio web a sua disposizione sui Blog. Nell'immettere i contenuti, il Cliente dichiara di attenersi alle presenti Condizioni Generali. <a name="11.5"></a><br>
  15.5. Qualora Gielle sia destinataria di azioni giudiziali su iniziativa di terze parti in merito all'attività esercitata o alla modalità di utilizzo del Servizio da parte di un Cliente, questi accetta espressamente di manlevare e tenere indenne Gielle da ogni pretesa, azione o effetto pregiudizievole connesso all'azione legale, obbligandosi a rimborsare ogni spesa e a risarcire ogni danno diretto e/o indiretto subito da Gielle per effetto delle suddette iniziative giudiziarie. <a name="11.6"></a><br>
  15.6. Il Cliente si obbliga inoltre a manlevare e tenere indenne Gielle da ogni e qualsiasi responsabilità, e conseguenti perdite, danni, costi e spese sofferti e/o sopportati da terzi e derivanti dall'utilizzazione del Sito in maniera non conforme alle obbligazioni contemplate dalle Condizioni Generali da parte di navigatori ovvero da terzi cui avesse consentito l'uso del Sito, ivi comprese le eventuali spese legali che dovessero essere sostenute da Gielle anche in ipotesi di danni pretesi da terzi a qualunque titolo. <br>
  15.7. Il Cliente si assume ogni responsabilità per ogni e qualsiasi danno o pregiudizio che potesse derivare a sé o a terzi dalla divulgazione, sottrazione, trasmissione a terzi non autorizzati del materiale che egli o terzi abbiano immesso <a name="11.8"></a>nei Blog.<br>
  15.8. Gielle dichiara di non svolgere in alcun caso un controllo editoriale sui contenuti dei Blog. Pertanto ogni responsabilità per danni e illeciti derivanti da tali contenuti sono da imputarsi esclusivamente ai Clienti<a name="12"></a><a name="13"></a></p>
<p><strong>16. Sospensione del Servizio</strong><a name="13.1"></a>:<br>
  16.1. Gielle si riserva il diritto di sospendere temporaneamente, senza alcuna preventiva comunicazione, l'erogazione del Servizio per il tempo strettamente necessario agli interventi tecnici necessari e/o opportuni per migliorare la qualità del Servizio. <a name="13.2"></a><br>
  16.2. Gielle potrà in ogni momento interrompere la prestazione del Servizio qualora ricorrano motivate ragioni di sicurezza o violazioni di riservatezza, dandone in tal caso comunicazione al Cliente. <a name="13.3"></a><br>
  16.3. Gielle si riserva altresì il diritto di interrompere immediatamente ed in via definitiva l'erogazione del Servizio al Cliente che, a seguito di verifiche risulti aver violato le disposizioni relative ai propri obblighi. <a name="14"></a></p>
<p><a name="15"></a><a name="16"></a><a name="17"></a><a name="18"></a><strong>17. Dati del Cliente:</strong><br>
  17.1. Il Cliente si impegna a comunicare a Gielle i propri dati personali necessari all'integrale e corretta esecuzione del contratto; garantisce, altresì, sotto la propria personale ed esclusiva responsabilità, che i predetti dati sono corretti, aggiornati e veritieri e che consentono di individuare la sua vera identità. Il Cliente si impegna a comunicare a Gielle ogni variazione dei dati forniti, tempestivamente e comunque entro e non oltre 15 (quindici) giorni dal verificarsi della predetta variazione con le modalità indicate sul sito www.wexplore.co, ed altresì a fornire in qualsiasi momento, previa richiesta di Gielle, prova adeguata della propria identità, del proprio domicilio o residenza e, se del caso, della propria qualità di legale rappresentante della persona giuridica richiedente o intestataria del Servizio. Al ricevimento della suddetta comunicazione, Gielle potrà richiedere al Cliente documentazione aggiuntiva diretta a dimostrare le variazioni comunicate. Nel caso in cui il Cliente ometta di fornire a Gielle la predetta comunicazione o la documentazione richiesta, oppure nel caso in cui abbia fornito a Gielle dati che risultino essere falsi, non attuali o incompleti o dati che Gielle abbia motivo, a suo insindacabile giudizio, di ritenere tali, Gielle si riserva il diritto di:<br>
  a) rifiutare la richiesta inoltrata dal Cliente avente ad oggetto operazioni da eseguire in riferimento al Servizio;<br>
  b) sospendere i servizi con effetto immediato, senza preavviso ed a tempo indeterminato; <br>
  c) annullare e/o interrompere senza preavviso eventuali operazioni di modifica dei dati associati al Servizio;<br>
  d) risolvere il contratto trattenendo a titolo di penale le somme pagate dal Cliente. Resta salvo, in ogni caso, il diritto di Gielle di richiedere al Cliente il risarcimento del maggior danno e resta, altresì, inteso che il Cliente non potrà avanzare nei confronti di Gielle alcuna richiesta di rimborso, indennizzo e/o risarcimento danni per il periodo di tempo in cui non ha usufruito del Servizio.</p>
<p><strong>18. Limitazioni di responsabilità di Gielle:</strong><br>
  18.1. Il Cliente riconosce e prende atto che l&rsquo;immissione delle informazioni nello spazio e la conseguente diffusione delle stesse nella rete internet, mediante i Servizi Wexplore, sono eseguite esclusivamente a proprio rischio. Il Cliente riconosce che la rete internet non è controllata da Gielle e che, per la sua peculiare struttura, nessuna entità pubblica o privata e neppure Gielle è in grado di garantire e monitorare le prestazioni e la funzionalità dei rami della rete e di controllare i contenuti delle informazioni che sono trasmesse mediante la propria rete. Per questo motivo il Cliente prende atto ed accetta che alcuna responsabilità può essere imputata a Gielle per la trasmissione o la ricezione di informazioni illegali di qualsiasi natura. Il Cliente accetta di manlevare Gielle per ogni azione di responsabilità che dovesse essere effettuata da Terzi relativamente a violazioni alle leggi nazionali o internazionali effettuate dal Cliente<br>
  18.2. Gielle a non assume, in nessun caso, alcuna responsabilità per le informazioni, i dati, i contenuti immessi o trasmessi e, comunque, trattati dal Cliente mediante il Servizio ed in genere per l&rsquo;uso fatto dal medesimo del predetto Servizio e si riserva di adottare qualsiasi iniziativa ed azione, a tutela dei propri diritti ed interessi, ivi compresa la comunicazione ai soggetti coinvolti dei dati utili a consentire l&rsquo;identificazione del Cliente. Alcuna responsabilità potrà esserle imputata qualora la fornitura del Servizio, con le precise caratteristiche richieste dal Cliente, sia condizionata al fatto del terzo (a titolo esemplificativo ma non esaustivo: fornitore di Gielle). Resta inteso, e di ciò il Cliente prende atto ed accetta, che Gielle non risponde in nessun modo dei danni subiti dallo stesso e/o da Terzi, direttamente o indirettamente, in conseguenza dell&rsquo;utilizzo dei servizi forniti.<br>
  18.3. Il Cliente, sollevando ora per allora Gielle da ogni relativa responsabilità, prende atto ed accetta che:<br>
  a) l&rsquo;utilizzo dei servizi forniti in collaborazione con altre infrastrutture (nazionali ed internazionali) è limitato ai confini e dalle norme stabilite dai gestori dei servizi medesimi, nonché dalle legislazioni vigenti nei Paesi che ospitano tali servizi e da quelle internazionali in materia;<br>
  b) restano sempre possibili interruzioni tecniche dei servizi dovute a guasti e malfunzionamenti delle macchine e dei software, siano essi di proprietà di Gielle o dei suoi fornitori;<br>
  c) la natura stessa dei servizi Internet, in cui molte entità sono coinvolte, non consente di fornire nessuna garanzia in riferimento alla costante fruibilità del servizio e/o sulla possibilità di raggiungere qualsiasi spazio web da tutto il mondo e/o sulla trasmissione e ricezione di informazioni <br>
  18.4. Gielle si impegna ad assicurare la migliore funzionalità del sistema, ma non assume alcuna responsabilità sia verso i propri Clienti sia verso Terzi per ritardi, cattivo funzionamento, sospensione e/o interruzione nell'erogazione del Servizio determinati da cause ad essa non imputabili, quali a titolo esemplificativo e non esaustivo: <br>
  a) caso fortuito, eventi catastrofici e forza maggiore; <br>
  b) fatto del terzo (a titolo esemplificativo ma non esaustivo: pubblicazione non autorizzata da parte di terzi dei testi immessi dal Cliente in qualsiasi area);<br>
  c) malfunzionamento o non conformità degli apparecchi di connessione di cui il Cliente si è dotato o comunque di quelli dal medesimo utilizzati; <br>
  d) manomissione o interventi sui servizi o sulle apparecchiature eseguiti dal Cliente o da parte di soggetti Terzi non autorizzati da Gielle; <br>
  e) errata utilizzazione o utilizzazione non conforme del Servizio da parte del Cliente, alle presenti Condizioni Generali o alle indicazioni contenute nei Sito comunque mancati adempimenti del Cliente;<br>
  f) guasti e malfunzionamenti delle macchine e dei software, siano essi di proprietà di Gielle o dei suoi fornitori.<br>
  Resta inteso che in tali casi, Gielle non risponderà di alcuna perdita, danno o lesione subiti e/o subendi dal Cliente e/o da Terzi, siano essi diretti o indiretti, prevedibili o imprevedibili, tra i quali a titolo esemplificativo e non esaustivo perdite economiche/finanziarie, di affari, di ricavi e di utili e/o di avviamento commerciale; il Cliente, pertanto, prende atto ed accetta che nulla avrà da pretendere da Gielle a titolo di risarcimento, indennizzo, rimborso o ad altro titolo.</p>
<p><strong>19. Riservatezza:</strong><br>
  19.1. Gielle ed il Cliente si impegnano reciprocamente a trattare come riservato ogni dato od informazione conosciuta o gestita in relazione alle attività per l'esecuzione del servizio fornito da Gielle sul Sito.</p>
<p><strong>20. Clausola risolutiva espressa:</strong><br>
  20.1. Il presente contratto si risolve di diritto, ai sensi e per gli effetti di cui all&rsquo;art. 1456 c.c, qualora il Cliente:<br>
  <em>a)</em> ceda tutto o parte del contratto a terzi; <br>
<em>b) </em>sia stato in precedenza o sia inadempiente ad ogni titolo nei confronti di Gielle, anche per servizi diversi da quello oggetto del presente contratto; <br>
  <em>c)</em> non provveda al pagamento del corrispettivo richiesto, ed il servizio sia stato nel frattempo attivato anche in deroga a quanto previsto dalle presenti Condizioni Generali; <br>
  <em>d) </em>utilizzi i servizi in modo diverso rispetto a quanto previsto dalle presenti Condizioni Generali; <br>
  <em>e) </em>violi le disposizioni contenute agli Artt. 10 e 16 delle presenti Condizioni <br>
  20.2. Per effetto della risoluzione Gielle sarà autorizzata ad interrompere la fornitura del Servizio senza alcun ulteriore preavviso. In tali ipotesi, il Cliente prende atto ed accetta che le somme pagate dal medesimo saranno trattenute da Gielle a titolo di penale, fatto salvo in ogni caso il risarcimento del maggior danno, senza che il Cliente possa avanzare alcuna richiesta di rimborso, indennizzo e/o risarcimento danni per il periodo di tempo in cui non ha usufruito del Servizio. <br>
  Resta inteso che la risoluzione di diritto sopra indicata opera senza pregiudizio per le altre ipotesi di risoluzione, ed in generale per gli altri strumenti di tutela previsti dalla legge.</p>
<p><strong>21. Disposizioni finali e comunicazioni: </strong><br>
  21.1. Il presente Contratto annulla e sostituisce ogni altra precedente intesa intervenuta tra le Parti, e costituisce la manifestazione integrale degli accordi conclusi tra le stesse. <br>
  21.2. Nessuna modifica aggiunta al presente contratto sarà valida ed efficace tra le Parti, se non specificatamente ed espressamente approvata per iscritto da entrambe. <br>
  21.3. In nessun caso eventuali inadempimenti e/o comportamenti del Cliente difformi alle presenti Condizioni, potranno essere considerati quali deroghe alle medesime o tacite accettazioni degli inadempimenti, anche se non contestati da Gielle. L'eventuale inerzia di Gielle nell'esercitare o far valere un qualsiasi diritto o clausola del Contratto, non costituisce rinuncia a tali diritti o clausole. <br>
  21.4. Tutte le comunicazioni al Cliente relative al presente rapporto contrattuale potranno essere effettuate da Gielle indistintamente, tramite posta elettronica, certificata e non, a mezzo di lettera raccomandata A.R., oppure a mezzo telefax ai recapiti indicati dal Cliente in fase di compilazione del Modulo e, in conseguenza, le medesime si considereranno da questi conosciute. Eventuali variazioni degli indirizzi del Cliente non comunicate a Gielle non saranno ad essa opponibili. <br>
  Tutte le comunicazioni che il Cliente intenda inviare a Gielle relativamente al presente contratto dovranno essere inviate ai recapiti presenti sul Sito.<br>
  21.5. L&rsquo;eventuale inefficacia e/o invalidità, totale o parziale, di una o più clausole delle presenti Condizioni Generali non comporterà l&rsquo;invalidità delle altre, le quali dovranno ritenersi pienamente valide ed efficaci. <br>
  21.6. Per quanto non espressamente previsto nelle presenti Condizioni Generali, le Parti fanno espresso rinvio, nei limiti in cui ciò sia compatibile, alle norme di legge vigenti al momento della conclusione del contratto. </p>
<p><strong>22. Legge applicabile e Foro competente</strong><br>
  22.1. Le presenti condizioni generali sono regolati dalla legge italiana. Per ogni e qualsiasi controversia relativa all'interpretazione, esecuzione e risoluzione del Contratto sarà esclusivamente competente il Foro di Milano, salvo il caso in cui il Cliente abbia agito e concluso il presente contratto in qualità di Consumatore per scopi estranei all'attività imprenditoriale o professionale svolta; in tal caso sarà esclusivamente competente il Foro del luogo dove il Cliente ha la propria residenza o domicilio, se ubicati sul territorio dello stato italiano.</p>
<p><strong>Clausole vessatorie</strong><strong> </strong><br>
  Ai sensi e per gli effetti di cui agli artt. 1341 e 1342 Cod. Civ., il Cliente, dopo averne presa attenta e specifica conoscenza e visione, approva e ed accetta espressamente le seguenti clausole:<br>
  2) Registrazione al Sito e conclusione del contratto di fornitura dei Servizi riservati agli Utenti e dei Servizi a Pagamento;<br>
  4) Modalità di registrazione;<br>
  5) Caratteristiche dei servizi;<br>
  6) Corrispettivi e modalità di pagamento dei Servizi a Pagamento;<br>
  7) Attivazione ed erogazione del servizio;<br>
  8) Durata, rinnovo, cessazione, recesso dal contratto;<br>
  9) Utilizzo dei blog;<br>
  10) Tutela minori;<br>
  11) Funzionalità dei Servizi;<br>
  12) Modifiche dei servizi e variazioni alle condizioni dell'offerta;<br>
  13) Cessione del Contratto;<br>
  14) Diritti di proprietà industriale e/o intellettuale – contenuti scaricabili;<br>
  15) Limitazione della responsabilità;<br>
  16) Sospensione del Servizio;<br>
  17) Dati del Cliente;<br>
  18) Limitazioni di responsabilità di Gielle;<br>
  20) Clausola risolutiva espressa;<br>
  21) Disposizioni finali e comunicazioni; <br>
  22) Legge applicabile e Foro competente.</p>
<div>
  <div> </div>
</div>
                                </div>
							</div>

							</div>
						</div>
					</div>
				</div>
</div>
</div>
